package actions

import (
	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop"
	"github.com/pkg/errors"
	"mmgitl.mattclark.guru/Anchorspace/dashboard/models"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Term)
// DB Table: Plural (terms)
// Resource: Plural (Terms)
// Path: Plural (/terms)
// View Template Folder: Plural (/templates/terms/)

// TermsResource is the resource for the Term model
type TermsResource struct {
	buffalo.Resource
}

// List gets all Terms. This function is mapped to the path
// GET /terms
func (v TermsResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	terms := &models.Terms{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all Terms from the DB
	if err := q.All(terms); err != nil {
		return errors.WithStack(err)
	}

	// Add the paginator to the context so it can be used in the template.
	c.Set("pagination", q.Paginator)

	return c.Render(200, r.Auto(c, terms))
}

// Show gets the data for one Term. This function is mapped to
// the path GET /terms/{term_id}
func (v TermsResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Term
	term := &models.Term{}

	// To find the Term the parameter term_id is used.
	if err := tx.Find(term, c.Param("term_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, term))
}

// New renders the form for creating a new Term.
// This function is mapped to the path GET /terms/new
func (v TermsResource) New(c buffalo.Context) error {
	current_user := c.Value("current_user").(*models.User)
	if !current_user.IsAdmin {
		c.Flash().Add("danger", "You don't have access to that!")
		return c.Render(404, r.HTML("index.html"))
	}

	c.Set("type_options", models.TermTypeOptions())
	return c.Render(200, r.Auto(c, &models.Term{}))
}

// Create adds a Term to the DB. This function is mapped to the
// path POST /terms
func (v TermsResource) Create(c buffalo.Context) error {
	current_user := c.Value("current_user").(*models.User)
	if !current_user.IsAdmin {
		c.Flash().Add("danger", "You don't have access to that!")
		return c.Render(404, r.HTML("index.html"))
	}

	// Allocate an empty Term
	term := &models.Term{}

	// Bind term to the html form elements
	if err := c.Bind(term); err != nil {
		return errors.WithStack(err)
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(term)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the new.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, term))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "Term was created successfully")

	// and redirect to the terms index page
	return c.Render(201, r.Auto(c, term))
}

// Edit renders a edit form for a Term. This function is
// mapped to the path GET /terms/{term_id}/edit
func (v TermsResource) Edit(c buffalo.Context) error {
	current_user := c.Value("current_user").(*models.User)
	if !current_user.IsAdmin {
		c.Flash().Add("danger", "You don't have access to that!")
		return c.Render(404, r.HTML("index.html"))
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Term
	term := &models.Term{}

	if err := tx.Find(term, c.Param("term_id")); err != nil {
		return c.Error(404, err)
	}

	c.Set("type_options", models.TermTypeOptions())
	return c.Render(200, r.Auto(c, term))
}

// Update changes a Term in the DB. This function is mapped to
// the path PUT /terms/{term_id}
func (v TermsResource) Update(c buffalo.Context) error {
	current_user := c.Value("current_user").(*models.User)
	if !current_user.IsAdmin {
		c.Flash().Add("danger", "You don't have access to that!")
		return c.Render(404, r.HTML("index.html"))
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Term
	term := &models.Term{}

	if err := tx.Find(term, c.Param("term_id")); err != nil {
		return c.Error(404, err)
	}

	// Bind Term to the html form elements
	if err := c.Bind(term); err != nil {
		return errors.WithStack(err)
	}

	verrs, err := tx.ValidateAndUpdate(term)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the edit.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, term))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "Term was updated successfully")

	// and redirect to the terms index page
	return c.Render(200, r.Auto(c, term))
}

// Destroy deletes a Term from the DB. This function is mapped
// to the path DELETE /terms/{term_id}
func (v TermsResource) Destroy(c buffalo.Context) error {
	current_user := c.Value("current_user").(*models.User)
	if !current_user.IsAdmin {
		c.Flash().Add("danger", "You don't have access to that!")
		return c.Render(404, r.HTML("index.html"))
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Term
	term := &models.Term{}

	// To find the Term the parameter term_id is used.
	if err := tx.Find(term, c.Param("term_id")); err != nil {
		return c.Error(404, err)
	}

	if err := tx.Destroy(term); err != nil {
		return errors.WithStack(err)
	}

	// If there are no errors set a flash message
	c.Flash().Add("success", "Term was destroyed successfully")

	// Redirect to the terms index page
	return c.Render(200, r.Auto(c, term))
}
