package actions

import (
	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop"
	"github.com/pkg/errors"
	"mmgitl.mattclark.guru/Anchorspace/dashboard/models"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Use)
// DB Table: Plural (uses)
// Resource: Plural (Uses)
// Path: Plural (/uses)
// View Template Folder: Plural (/templates/uses/)

// UsesResource is the resource for the Use model
type UsesResource struct {
	buffalo.Resource
}

// List gets all Uses. This function is mapped to the path
// GET /uses
func (v UsesResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	uses := &models.Uses{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all Uses from the DB
	if err := q.All(uses); err != nil {
		return errors.WithStack(err)
	}

	// Add the paginator to the context so it can be used in the template.
	c.Set("pagination", q.Paginator)

	return c.Render(200, r.Auto(c, uses))
}

// Show gets the data for one Use. This function is mapped to
// the path GET /uses/{use_id}
func (v UsesResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Use
	use := &models.Use{}

	// To find the Use the parameter use_id is used.
	if err := tx.Find(use, c.Param("use_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, use))
}

// New renders the form for creating a new Use.
// This function is mapped to the path GET /uses/new
func (v UsesResource) New(c buffalo.Context) error {
	current_user := c.Value("current_user").(*models.User)
	if !current_user.IsAdmin {
		c.Flash().Add("danger", "You don't have access to that!")
		return c.Render(404, r.HTML("index.html"))
	}

	return c.Render(200, r.Auto(c, &models.Use{}))
}

// Create adds a Use to the DB. This function is mapped to the
// path POST /uses
func (v UsesResource) Create(c buffalo.Context) error {
	current_user := c.Value("current_user").(*models.User)
	if !current_user.IsAdmin {
		c.Flash().Add("danger", "You don't have access to that!")
		return c.Render(404, r.HTML("index.html"))
	}

	// Allocate an empty Use
	use := &models.Use{}

	// Bind use to the html form elements
	if err := c.Bind(use); err != nil {
		return errors.WithStack(err)
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(use)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the new.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, use))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "Use was created successfully")

	// and redirect to the uses index page
	return c.Render(201, r.Auto(c, use))
}

// Edit renders a edit form for a Use. This function is
// mapped to the path GET /uses/{use_id}/edit
func (v UsesResource) Edit(c buffalo.Context) error {
	current_user := c.Value("current_user").(*models.User)
	if !current_user.IsAdmin {
		c.Flash().Add("danger", "You don't have access to that!")
		return c.Render(404, r.HTML("index.html"))
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Use
	use := &models.Use{}

	if err := tx.Find(use, c.Param("use_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, use))
}

// Update changes a Use in the DB. This function is mapped to
// the path PUT /uses/{use_id}
func (v UsesResource) Update(c buffalo.Context) error {
	current_user := c.Value("current_user").(*models.User)
	if !current_user.IsAdmin {
		c.Flash().Add("danger", "You don't have access to that!")
		return c.Render(404, r.HTML("index.html"))
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Use
	use := &models.Use{}

	if err := tx.Find(use, c.Param("use_id")); err != nil {
		return c.Error(404, err)
	}

	// Bind Use to the html form elements
	if err := c.Bind(use); err != nil {
		return errors.WithStack(err)
	}

	verrs, err := tx.ValidateAndUpdate(use)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the edit.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, use))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "Use was updated successfully")

	// and redirect to the uses index page
	return c.Render(200, r.Auto(c, use))
}

// Destroy deletes a Use from the DB. This function is mapped
// to the path DELETE /uses/{use_id}
func (v UsesResource) Destroy(c buffalo.Context) error {
	current_user := c.Value("current_user").(*models.User)
	if !current_user.IsAdmin {
		c.Flash().Add("danger", "You don't have access to that!")
		return c.Render(404, r.HTML("index.html"))
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Use
	use := &models.Use{}

	// To find the Use the parameter use_id is used.
	if err := tx.Find(use, c.Param("use_id")); err != nil {
		return c.Error(404, err)
	}

	if err := tx.Destroy(use); err != nil {
		return errors.WithStack(err)
	}

	// If there are no errors set a flash message
	c.Flash().Add("success", "Use was destroyed successfully")

	// Redirect to the uses index page
	return c.Render(200, r.Auto(c, use))
}
